<?php declare(strict_types=1);

namespace Lemonade\Feed\Infrastructure\Xsl;

final class SitemapXslTranslations
{
    /**
     * @return array{
     *   title: string,
     *   breadcrumb: string,
     *   heading: string,
     *   generated: string,
     *   columns: array{
     *     url: string,
     *     priority: string,
     *     frequency: string,
     *     lastmod: string
     *   },
     *   datatable: array{
     *     search: string,
     *     lengthMenu: string,
     *     info: string,
     *     infoFiltered: string,
     *     infoEmpty: string,
     *     zeroRecords: string,
     *     paginate: array{
     *       first: string,
     *       last: string,
     *       next: string,
     *       previous: string
     *     }
     *   }
     * }
     */
    public static function get(string $lang): array
    {
        return match ($lang) {
            'en' => self::en(),
            'de' => self::de(),
            'fr' => self::fr(),
            'ru' => self::ru(),
            'sk' => self::sk(),
            'es' => self::es(),
            'it' => self::it(),
            'pl' => self::pl(),
            'hu' => self::hu(),
            'pt' => self::pt(),
            'nl' => self::nl(),
            'ro' => self::ro(),
            'bg' => self::bg(),
            default => self::cs(),
        };

    }

    private static function cs(): array
    {
        return [
            'title'      => 'XML Sitemap',
            'breadcrumb' => 'Hlavní strana',
            'heading'    => 'XML Sitemapa',
            'generated'  => 'Vygenerováno pomocí <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, jedná se o XML sitemapu, která je určena pro vyhledávače.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorita',
                'frequency' => 'Frekvence',
                'lastmod'   => 'Aktualizace',
            ],
            'datatable' => [
                'search'       => 'Vyhledat:',
                'lengthMenu'   => 'Zobrazit _MENU_ záznamů',
                'info'         => 'Zobrazuji _START_ až _END_ z _TOTAL_ záznamů',
                'infoFiltered' => '(filtrováno z celkových _MAX_ záznamů)',
                'infoEmpty'    => 'Žádné záznamy k zobrazení',
                'zeroRecords'  => 'Nenalezeny žádné odpovídající záznamy',
                'paginate'     => [
                    'first'    => 'První',
                    'last'     => 'Poslední',
                    'next'     => 'Další',
                    'previous' => 'Předchozí',
                ],
            ],
        ];
    }

    private static function en(): array
    {
        return [
            'title'      => 'XML Sitemap',
            'breadcrumb' => 'Home',
            'heading'    => 'XML Sitemap',
            'generated'  => 'Generated by <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, this is an XML sitemap intended for search engines.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priority',
                'frequency' => 'Frequency',
                'lastmod'   => 'Last modified',
            ],
            'datatable' => [
                'search'       => 'Search:',
                'lengthMenu'   => 'Show _MENU_ entries',
                'info'         => 'Showing _START_ to _END_ of _TOTAL_ entries',
                'infoFiltered' => '(filtered from _MAX_ total entries)',
                'infoEmpty'    => 'No entries to show',
                'zeroRecords'  => 'No matching records found',
                'paginate'     => [
                    'first'    => 'First',
                    'last'     => 'Last',
                    'next'     => 'Next',
                    'previous' => 'Previous',
                ],
            ],
        ];
    }

    private static function de(): array
    {
        return [
            'title'      => 'XML-Sitemap',
            'breadcrumb' => 'Startseite',
            'heading'    => 'XML-Sitemap',
            'generated'  => 'Erstellt mit <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, dies ist eine XML-Sitemap für Suchmaschinen.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorität',
                'frequency' => 'Frequenz',
                'lastmod'   => 'Zuletzt geändert',
            ],
            'datatable' => [
                'search'       => 'Suchen:',
                'lengthMenu'   => 'Zeige _MENU_ Einträge',
                'info'         => 'Zeige _START_ bis _END_ von _TOTAL_ Einträgen',
                'infoFiltered' => '(gefiltert aus insgesamt _MAX_ Einträgen)',
                'infoEmpty'    => 'Keine Einträge vorhanden',
                'zeroRecords'  => 'Keine passenden Einträge gefunden',
                'paginate'     => [
                    'first'    => 'Erste',
                    'last'     => 'Letzte',
                    'next'     => 'Nächste',
                    'previous' => 'Vorherige',
                ],
            ],
        ];
    }

    private static function fr(): array
    {
        return [
            'title'      => 'Plan du site XML',
            'breadcrumb' => 'Accueil',
            'heading'    => 'Plan du site XML',
            'generated'  => 'Généré par <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, ceci est un plan de site XML destiné aux moteurs de recherche.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorité',
                'frequency' => 'Fréquence',
                'lastmod'   => 'Dernière modification',
            ],
            'datatable' => [
                'search'       => 'Rechercher :',
                'lengthMenu'   => 'Afficher _MENU_ entrées',
                'info'         => 'Affichage de _START_ à _END_ sur _TOTAL_ entrées',
                'infoFiltered' => '(filtré à partir de _MAX_ entrées au total)',
                'infoEmpty'    => 'Aucune entrée à afficher',
                'zeroRecords'  => 'Aucun enregistrement correspondant trouvé',
                'paginate'     => [
                    'first'    => 'Premier',
                    'last'     => 'Dernier',
                    'next'     => 'Suivant',
                    'previous' => 'Précédent',
                ],
            ],
        ];
    }

    private static function ru(): array
    {
        return [
            'title'      => 'XML-карта сайта',
            'breadcrumb' => 'Главная',
            'heading'    => 'XML-карта сайта',
            'generated'  => 'Сгенерировано с помощью <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, это XML-карта сайта для поисковых систем.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Приоритет',
                'frequency' => 'Частота',
                'lastmod'   => 'Последнее изменение',
            ],
            'datatable' => [
                'search'       => 'Поиск:',
                'lengthMenu'   => 'Показать _MENU_ записей',
                'info'         => 'Показаны записи с _START_ по _END_ из _TOTAL_',
                'infoFiltered' => '(отфильтровано из _MAX_ записей)',
                'infoEmpty'    => 'Нет записей для отображения',
                'zeroRecords'  => 'Совпадений не найдено',
                'paginate'     => [
                    'first'    => 'Первая',
                    'last'     => 'Последняя',
                    'next'     => 'Следующая',
                    'previous' => 'Предыдущая',
                ],
            ],
        ];
    }

    private static function sk(): array
    {
        return [
            'title'      => 'XML Sitemap',
            'breadcrumb' => 'Hlavná stránka',
            'heading'    => 'XML Sitemap',
            'generated'  => 'Vygenerované pomocou <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, toto je XML sitemap určená pre vyhľadávače.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorita',
                'frequency' => 'Frekvencia',
                'lastmod'   => 'Aktualizácia',
            ],
            'datatable' => [
                'search'       => 'Vyhľadať:',
                'lengthMenu'   => 'Zobraziť _MENU_ záznamov',
                'info'         => 'Zobrazené _START_ až _END_ z _TOTAL_ záznamov',
                'infoFiltered' => '(filtrované z celkových _MAX_ záznamov)',
                'infoEmpty'    => 'Žiadne záznamy na zobrazenie',
                'zeroRecords'  => 'Nenašli sa žiadne zodpovedajúce záznamy',
                'paginate'     => [
                    'first'    => 'Prvá',
                    'last'     => 'Posledná',
                    'next'     => 'Ďalšia',
                    'previous' => 'Predchádzajúca',
                ],
            ],
        ];
    }

    private static function es(): array
    {
        return [
            'title'      => 'Mapa del sitio XML',
            'breadcrumb' => 'Inicio',
            'heading'    => 'Mapa del sitio XML',
            'generated'  => 'Generado por <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, este es un mapa del sitio XML destinado a los motores de búsqueda.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Prioridad',
                'frequency' => 'Frecuencia',
                'lastmod'   => 'Última modificación',
            ],
            'datatable' => [
                'search'       => 'Buscar:',
                'lengthMenu'   => 'Mostrar _MENU_ entradas',
                'info'         => 'Mostrando de _START_ a _END_ de _TOTAL_ entradas',
                'infoFiltered' => '(filtrado de un total de _MAX_ entradas)',
                'infoEmpty'    => 'No hay entradas para mostrar',
                'zeroRecords'  => 'No se encontraron registros coincidentes',
                'paginate'     => [
                    'first'    => 'Primera',
                    'last'     => 'Última',
                    'next'     => 'Siguiente',
                    'previous' => 'Anterior',
                ],
            ],
        ];
    }

    private static function it(): array
    {
        return [
            'title'      => 'Mappa del sito XML',
            'breadcrumb' => 'Home',
            'heading'    => 'Mappa del sito XML',
            'generated'  => 'Generato da <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, questa è una mappa del sito XML destinata ai motori di ricerca.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorità',
                'frequency' => 'Frequenza',
                'lastmod'   => 'Ultima modifica',
            ],
            'datatable' => [
                'search'       => 'Cerca:',
                'lengthMenu'   => 'Mostra _MENU_ voci',
                'info'         => 'Visualizzazione da _START_ a _END_ di _TOTAL_ voci',
                'infoFiltered' => '(filtrato da un totale di _MAX_ voci)',
                'infoEmpty'    => 'Nessuna voce da mostrare',
                'zeroRecords'  => 'Nessun record corrispondente trovato',
                'paginate'     => [
                    'first'    => 'Prima',
                    'last'     => 'Ultima',
                    'next'     => 'Successiva',
                    'previous' => 'Precedente',
                ],
            ],
        ];
    }

    private static function pl(): array
    {
        return [
            'title'      => 'Mapa witryny XML',
            'breadcrumb' => 'Strona główna',
            'heading'    => 'Mapa witryny XML',
            'generated'  => 'Wygenerowane przez <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, jest to mapa witryny XML przeznaczona dla wyszukiwarek.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorytet',
                'frequency' => 'Częstotliwość',
                'lastmod'   => 'Ostatnia modyfikacja',
            ],
            'datatable' => [
                'search'       => 'Szukaj:',
                'lengthMenu'   => 'Pokaż _MENU_ rekordów',
                'info'         => 'Wyświetlanie od _START_ do _END_ z _TOTAL_ rekordów',
                'infoFiltered' => '(filtrowano z _MAX_ rekordów)',
                'infoEmpty'    => 'Brak rekordów do wyświetlenia',
                'zeroRecords'  => 'Nie znaleziono pasujących rekordów',
                'paginate'     => [
                    'first'    => 'Pierwsza',
                    'last'     => 'Ostatnia',
                    'next'     => 'Następna',
                    'previous' => 'Poprzednia',
                ],
            ],
        ];
    }

    private static function hu(): array
    {
        return [
            'title'      => 'XML webhelytérkép',
            'breadcrumb' => 'Főoldal',
            'heading'    => 'XML webhelytérkép',
            'generated'  => 'Készült a <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a> segítségével, ez egy XML webhelytérkép keresőmotorok számára.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Prioritás',
                'frequency' => 'Gyakoriság',
                'lastmod'   => 'Utolsó módosítás',
            ],
            'datatable' => [
                'search'       => 'Keresés:',
                'lengthMenu'   => 'Mutass _MENU_ bejegyzést',
                'info'         => '_START_ – _END_ / _TOTAL_ bejegyzés',
                'infoFiltered' => '(_MAX_ bejegyzésből szűrve)',
                'infoEmpty'    => 'Nincs megjeleníthető bejegyzés',
                'zeroRecords'  => 'Nincs találat',
                'paginate'     => [
                    'first'    => 'Első',
                    'last'     => 'Utolsó',
                    'next'     => 'Következő',
                    'previous' => 'Előző',
                ],
            ],
        ];
    }

    private static function pt(): array
    {
        return [
            'title'      => 'Mapa do site XML',
            'breadcrumb' => 'Início',
            'heading'    => 'Mapa do site XML',
            'generated'  => 'Gerado por <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, este é um mapa do site XML destinado a mecanismos de busca.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Prioridade',
                'frequency' => 'Frequência',
                'lastmod'   => 'Última modificação',
            ],
            'datatable' => [
                'search'       => 'Pesquisar:',
                'lengthMenu'   => 'Mostrar _MENU_ entradas',
                'info'         => 'Mostrando de _START_ a _END_ de _TOTAL_ entradas',
                'infoFiltered' => '(filtrado de _MAX_ entradas no total)',
                'infoEmpty'    => 'Nenhuma entrada para mostrar',
                'zeroRecords'  => 'Nenhum registro correspondente encontrado',
                'paginate'     => [
                    'first'    => 'Primeira',
                    'last'     => 'Última',
                    'next'     => 'Próxima',
                    'previous' => 'Anterior',
                ],
            ],
        ];
    }

    private static function nl(): array
    {
        return [
            'title'      => 'XML-sitemap',
            'breadcrumb' => 'Home',
            'heading'    => 'XML-sitemap',
            'generated'  => 'Gegenereerd door <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, dit is een XML-sitemap bedoeld voor zoekmachines.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Prioriteit',
                'frequency' => 'Frequentie',
                'lastmod'   => 'Laatst gewijzigd',
            ],
            'datatable' => [
                'search'       => 'Zoeken:',
                'lengthMenu'   => 'Toon _MENU_ items',
                'info'         => 'Toont _START_ tot _END_ van _TOTAL_ items',
                'infoFiltered' => '(gefilterd uit _MAX_ items)',
                'infoEmpty'    => 'Geen items om te tonen',
                'zeroRecords'  => 'Geen overeenkomende records gevonden',
                'paginate'     => [
                    'first'    => 'Eerste',
                    'last'     => 'Laatste',
                    'next'     => 'Volgende',
                    'previous' => 'Vorige',
                ],
            ],
        ];
    }

    private static function ro(): array
    {
        return [
            'title'      => 'Hartă site XML',
            'breadcrumb' => 'Acasă',
            'heading'    => 'Hartă site XML',
            'generated'  => 'Generat de <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, aceasta este o hartă a site-ului XML destinată motoarelor de căutare.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Prioritate',
                'frequency' => 'Frecvență',
                'lastmod'   => 'Ultima modificare',
            ],
            'datatable' => [
                'search'       => 'Căutare:',
                'lengthMenu'   => 'Afișează _MENU_ înregistrări',
                'info'         => 'Afișare de la _START_ la _END_ din _TOTAL_ înregistrări',
                'infoFiltered' => '(filtrat din _MAX_ înregistrări în total)',
                'infoEmpty'    => 'Nicio înregistrare de afișat',
                'zeroRecords'  => 'Nu au fost găsite înregistrări corespunzătoare',
                'paginate'     => [
                    'first'    => 'Prima',
                    'last'     => 'Ultima',
                    'next'     => 'Următoarea',
                    'previous' => 'Anterioară',
                ],
            ],
        ];
    }

    private static function bg(): array
    {
        return [
            'title'      => 'XML карта на сайта',
            'breadcrumb' => 'Начало',
            'heading'    => 'XML карта на сайта',
            'generated'  => 'Генерирано от <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, това е XML карта на сайта за търсачките.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Приоритет',
                'frequency' => 'Честота',
                'lastmod'   => 'Последна промяна',
            ],
            'datatable' => [
                'search'       => 'Търсене:',
                'lengthMenu'   => 'Показване на _MENU_ записа',
                'info'         => 'Показване от _START_ до _END_ от общо _TOTAL_ записа',
                'infoFiltered' => '(филтрирано от общо _MAX_ записа)',
                'infoEmpty'    => 'Няма записи за показване',
                'zeroRecords'  => 'Няма намерени съвпадения',
                'paginate'     => [
                    'first'    => 'Първа',
                    'last'     => 'Последна',
                    'next'     => 'Следваща',
                    'previous' => 'Предишна',
                ],
            ],
        ];
    }

}
