<?php declare(strict_types=1);

namespace Lemonade\Feed\Infrastructure\Xsl;

final class SitemapXslTranslations
{
    /**
     * @return array{
     *   title: string,
     *   breadcrumb: string,
     *   heading: string,
     *   generated: string,
     *   columns: array{
     *     url: string,
     *     priority: string,
     *     frequency: string,
     *     lastmod: string
     *   },
     *   datatable: array{
     *     search: string,
     *     lengthMenu: string,
     *     info: string,
     *     infoFiltered: string,
     *     infoEmpty: string,
     *     zeroRecords: string,
     *     paginate: array{
     *       first: string,
     *       last: string,
     *       next: string,
     *       previous: string
     *     }
     *   }
     * }
     */
    public static function get(string $lang): array
    {
        return match ($lang) {
            'en' => self::en(),
            'de' => self::de(),
            'fr' => self::fr(),
            'ru' => self::ru(),
            'sk' => self::sk(),
            default => self::cs(),
        };
    }

    private static function cs(): array
    {
        return [
            'title'      => 'XML Sitemap',
            'breadcrumb' => 'Hlavní strana',
            'heading'    => 'XML Sitemapa',
            'generated'  => 'Vygenerováno pomocí <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, jedná se o XML sitemapu, která je určena pro vyhledávače.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorita',
                'frequency' => 'Frekvence',
                'lastmod'   => 'Aktualizace',
            ],
            'datatable' => [
                'search'       => 'Vyhledat:',
                'lengthMenu'   => 'Zobrazit _MENU_ záznamů',
                'info'         => 'Zobrazuji _START_ až _END_ z _TOTAL_ záznamů',
                'infoFiltered' => '(filtrováno z celkových _MAX_ záznamů)',
                'infoEmpty'    => 'Žádné záznamy k zobrazení',
                'zeroRecords'  => 'Nenalezeny žádné odpovídající záznamy',
                'paginate'     => [
                    'first'    => 'První',
                    'last'     => 'Poslední',
                    'next'     => 'Další',
                    'previous' => 'Předchozí',
                ],
            ],
        ];
    }

    private static function en(): array
    {
        return [
            'title'      => 'XML Sitemap',
            'breadcrumb' => 'Home',
            'heading'    => 'XML Sitemap',
            'generated'  => 'Generated by <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, this is an XML sitemap intended for search engines.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priority',
                'frequency' => 'Frequency',
                'lastmod'   => 'Last modified',
            ],
            'datatable' => [
                'search'       => 'Search:',
                'lengthMenu'   => 'Show _MENU_ entries',
                'info'         => 'Showing _START_ to _END_ of _TOTAL_ entries',
                'infoFiltered' => '(filtered from _MAX_ total entries)',
                'infoEmpty'    => 'No entries to show',
                'zeroRecords'  => 'No matching records found',
                'paginate'     => [
                    'first'    => 'First',
                    'last'     => 'Last',
                    'next'     => 'Next',
                    'previous' => 'Previous',
                ],
            ],
        ];
    }

    private static function de(): array
    {
        return [
            'title'      => 'XML-Sitemap',
            'breadcrumb' => 'Startseite',
            'heading'    => 'XML-Sitemap',
            'generated'  => 'Erstellt mit <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, dies ist eine XML-Sitemap für Suchmaschinen.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorität',
                'frequency' => 'Frequenz',
                'lastmod'   => 'Zuletzt geändert',
            ],
            'datatable' => [
                'search'       => 'Suchen:',
                'lengthMenu'   => 'Zeige _MENU_ Einträge',
                'info'         => 'Zeige _START_ bis _END_ von _TOTAL_ Einträgen',
                'infoFiltered' => '(gefiltert aus insgesamt _MAX_ Einträgen)',
                'infoEmpty'    => 'Keine Einträge vorhanden',
                'zeroRecords'  => 'Keine passenden Einträge gefunden',
                'paginate'     => [
                    'first'    => 'Erste',
                    'last'     => 'Letzte',
                    'next'     => 'Nächste',
                    'previous' => 'Vorherige',
                ],
            ],
        ];
    }

    private static function fr(): array
    {
        return [
            'title'      => 'Plan du site XML',
            'breadcrumb' => 'Accueil',
            'heading'    => 'Plan du site XML',
            'generated'  => 'Généré par <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, ceci est un plan de site XML destiné aux moteurs de recherche.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorité',
                'frequency' => 'Fréquence',
                'lastmod'   => 'Dernière modification',
            ],
            'datatable' => [
                'search'       => 'Rechercher :',
                'lengthMenu'   => 'Afficher _MENU_ entrées',
                'info'         => 'Affichage de _START_ à _END_ sur _TOTAL_ entrées',
                'infoFiltered' => '(filtré à partir de _MAX_ entrées au total)',
                'infoEmpty'    => 'Aucune entrée à afficher',
                'zeroRecords'  => 'Aucun enregistrement correspondant trouvé',
                'paginate'     => [
                    'first'    => 'Premier',
                    'last'     => 'Dernier',
                    'next'     => 'Suivant',
                    'previous' => 'Précédent',
                ],
            ],
        ];
    }

    private static function ru(): array
    {
        return [
            'title'      => 'XML-карта сайта',
            'breadcrumb' => 'Главная',
            'heading'    => 'XML-карта сайта',
            'generated'  => 'Сгенерировано с помощью <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, это XML-карта сайта для поисковых систем.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Приоритет',
                'frequency' => 'Частота',
                'lastmod'   => 'Последнее изменение',
            ],
            'datatable' => [
                'search'       => 'Поиск:',
                'lengthMenu'   => 'Показать _MENU_ записей',
                'info'         => 'Показаны записи с _START_ по _END_ из _TOTAL_',
                'infoFiltered' => '(отфильтровано из _MAX_ записей)',
                'infoEmpty'    => 'Нет записей для отображения',
                'zeroRecords'  => 'Совпадений не найдено',
                'paginate'     => [
                    'first'    => 'Первая',
                    'last'     => 'Последняя',
                    'next'     => 'Следующая',
                    'previous' => 'Предыдущая',
                ],
            ],
        ];
    }

    private static function sk(): array
    {
        return [
            'title'      => 'XML Sitemap',
            'breadcrumb' => 'Hlavná stránka',
            'heading'    => 'XML Sitemap',
            'generated'  => 'Vygenerované pomocou <a href="https://lemonadeframework.cz/" target="_blank">Lemonade Framework</a>, toto je XML sitemap určená pre vyhľadávače.',
            'columns'    => [
                'url'       => 'URL',
                'priority'  => 'Priorita',
                'frequency' => 'Frekvencia',
                'lastmod'   => 'Aktualizácia',
            ],
            'datatable' => [
                'search'       => 'Vyhľadať:',
                'lengthMenu'   => 'Zobraziť _MENU_ záznamov',
                'info'         => 'Zobrazené _START_ až _END_ z _TOTAL_ záznamov',
                'infoFiltered' => '(filtrované z celkových _MAX_ záznamov)',
                'infoEmpty'    => 'Žiadne záznamy na zobrazenie',
                'zeroRecords'  => 'Nenašli sa žiadne zodpovedajúce záznamy',
                'paginate'     => [
                    'first'    => 'Prvá',
                    'last'     => 'Posledná',
                    'next'     => 'Ďalšia',
                    'previous' => 'Predchádzajúca',
                ],
            ],
        ];
    }
}
